kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-inline
spec:
  containers:
    - name: my-frontend
      image: busybox:1.32.0
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: ["sh", "-c", "while true; do echo hello >> /data/test; sleep 100; done"]
  volumes:
    - name: my-csi-volume
      csi:
        driver: katbox.csi.paypal.com
